In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

In [2]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [4]:
arr1.data

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [14]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [15]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [16]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [19]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [20]:
np.random.random(4)

array([0.91870132, 0.88210423, 0.49181815, 0.49588164])

In [21]:
np.random.randint(0, 500, 5)

array([ 94, 179, 307,  96,  43])

In [22]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [24]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [25]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [27]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [28]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [29]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [30]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [31]:
b2 = np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [32]:
arr1

array([10, 20, 30, 40, 50, 60])

In [33]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [34]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [35]:
arr2.sum()

190

In [36]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [37]:
#min(), max(), argmin(), argmax(), mean(), median(), var(), std()

In [38]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [39]:
#sum(), min(), max()

In [40]:
np.amin(A, axis = 0) 

array([1, 2, 1, 0])

In [41]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [42]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [43]:
a = np.array([7,5,3,9,0,2])

In [44]:
a[0]

7

In [45]:
a[-1]

2

In [46]:
a[1:4]

array([5, 3, 9])

In [47]:
a[-3:-1]

array([9, 0])

In [48]:
#Bir dizideki elemanları değiştirme

In [49]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [50]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [51]:
ar2 = np.array([10,20,30,10,10,20,20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [53]:
rep1 = np.where(ar2 == 10, 99,ar2)
print(rep1)

[99 20 30 99 99 20 20]


In [54]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [56]:
#Eksik Değerlerle İlgilenme

In [57]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [58]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [59]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [60]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [62]:
np.isnan(a).any()

False

In [63]:
A = np.array([[1,2,np.nan, 4], [np.nan, 6,7,8], [10, np.nan, 12, 13], [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [64]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [65]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [66]:
#Stacking 

In [67]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
np.vstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [69]:
np.hstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [71]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [72]:
np.intersect1d(c1, c2)

array([20, 40, 60])

In [74]:
np.setdiff1d(c2, c1)

array([12, 33, 55])

In [75]:
a1 = np.arange(0, 60)
a1[np.where((a1 > 20) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [77]:
a1 = np.arange(0, 60)
a1[np.where(((a1 > 20) & (a1 < 35)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [78]:
a1[np.where(np.logical_and(a1 > 20, a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [79]:
#Reverse

In [80]:
a4 = np.arange(10, 30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [81]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [82]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [83]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45, 25, 75, 15], [12, 9, 77, 4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [84]:
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [85]:
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [86]:
a3[::-1, ::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [87]:
#Sorting (Sıralama)

In [88]:
a = np.array([10,5,2,22,12,92,17,33])

In [89]:
np.sort(a) #her zaman küçükten büyüğe (ascending)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [90]:
b = np.sort(a) #büyükten küçüğe yapmak istersek (descending)
b = b[::-1]
b

array([92, 33, 22, 17, 12, 10,  5,  2])

In [91]:
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

In [92]:
a[::-1].sort()
a

array([92, 33, 22, 17, 12, 10,  5,  2])

In [93]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [94]:
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [95]:
np.sort(a3, axis = 1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [96]:
np.sort(a3, axis = 0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [97]:
p = np.arange(0, 50)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [98]:
np.random.shuffle(p)
p

array([27, 26, 35, 41, 45, 43,  6,  4, 34, 16,  3,  1, 31, 25, 48, 40, 21,
        2, 13, 47,  5, 37, 14, 23, 32, 22,  8, 20, 44, 28, 36, 10, 30, 19,
       24, 29, 33, 42, 11, 17, 12,  0, 15, 49,  7, 18,  9, 46, 38, 39])

In [99]:
n = 4
p[np.argsort(p)[-n:]]

array([46, 47, 48, 49])

In [100]:
p[np.argsort(-p)[-n:]]

array([3, 2, 1, 0])

In [101]:
#Dosya yükleme ve kaydetme işlemleri

In [102]:
p4 = np.loadtxt('mydata/sample.txt', dtype = np.integer)
p4

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [103]:
p5 = np.genfromtxt('mydata/sample0.txt', dtype = 'str')
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')

In [104]:
p5[0]

array(['Dogu', 'Turkey', 'Football'], dtype='<U10')

In [105]:
p5[:, 0]

array(['Dogu', 'John', 'Paul'], dtype='<U10')

In [106]:
np.loadtxt('mydata/sample.txt', delimiter = ' ', usecols = (0, 2))

array([[24., 88.],
       [ 1.,  8.],
       [33., 99.],
       [39., 98.],
       [22., 87.]])

In [107]:
p7 = np.arange(10, 200, 11)

In [108]:
p7

array([ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109, 120, 131, 142,
       153, 164, 175, 186, 197])

In [109]:
np.savetxt('mydata/1904DEB.csv', p7, delimiter = ',')