In [3]:
#Tensörler
import numpy as np

In [6]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100, 200, 300], [400, 500, 600], [700, 800, 900]],
])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [5]:
T2= np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]],
    
])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [7]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [8]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [9]:
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [10]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
D = T1 / T2 # np.divide(T1, T2)
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [15]:
from scipy import linalg

In [16]:
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]


In [17]:
print("linalg.inv(A).dot(b) Matrix Inverse ile Denklem Takımı Çözümü")
print(linalg.inv(A).dot(b)) #slow

linalg.inv(A).dot(b) Matrix Inverse ile Denklem Takımı Çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [18]:
print("np.linalg.solve(A, b) ile Denklem Takımı Çözümü")
print(np.linalg.solve(A, b)) #fast

np.linalg.solve(A, b) ile Denklem Takımı Çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [19]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [20]:
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [21]:
import pandas as pd

In [22]:
#Seriler ve Veri Çerçeveleri (DataFrame)

In [23]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32